name=input("Enter student name:")
print("---------------------->")
admission_fee=int(input("Enter Admisission fee:"))
tuition_fee=int(input("Enter Tuition fee:"))
hostel_fee=int(input("Enter Hostel fee:"))
total_fee=admission_fee+tuition_fee+hostel_fee
print("---------------------->")
print("Student Name:",name)
print("Admission fee:",admission_fee)
print("Tuition Fee:",tuition_fee)
print("Hostel Fee:",hostel_fee)
print("Total fee:",total_fee)
